### PR TITLE
fixing a bug I found

### PR DESCRIPTION
**Pull request by Vic-ST**
Fixing some random bug.

### CODE REVIEW

**Comment by Elisebassett** [comment]
PS. How did you find this project? Have we met?

**Comment by Vic-ST** [comment]
@Elisebassett I have been watching you for a long time. Sorry, just kidding. I was looking for projects to contribute to for the hacktoberfest event. I found your project and I thought "I can get some PRs on this.". https://hacktoberfest.digitalocean.com/

**Comment by Elisebassett** [comment]
Hahaha well awesome! Yeah, I'm actually in a coding bootcamp right now, and
this was just one of my assignments. Crazy someone found me at all haha

**Comment by Vic-ST** [comment]
What bootcamp is it?

**Comment by Elisebassett** [comment]
New York Code and Design Academy. How long have you been coding?

**Comment by Vic-ST** [comment]
since I was eight years old

**Comment by Elisebassett** [comment]
How old are you now?

**Comment by Vic-ST** [comment]
a reasonable age.

**Comment by Elisebassett** [comment]
Hahaha ok. So at least 2 years experience.

**Comment by StevenCopeland** [comment]
at least 5 years. That does not mean I am 12

**Pull request closed without merging**
